### PR TITLE
Remember last open ticket and continue from there

### PR DESCRIPTION
**Pull request by Rast1234**
Hey! I added a persistent state for last opened ticket number and a button to start from this ticket. Hope you find this useful.
image
image

### CODE REVIEW

**Comment by Asasay** [comment]
If, for example, you reach the ticket №400 in category "A", and then change the category to "AM", in which there are only 327 tickets, an error will occur when you try to continue.

**Comment by Asasay** [comment]
If, for example, you reach the ticket №400 in category "A", and then change the category to "AM", in which there are only 327 tickets, an error will occur when you try to continue.

**Comment by Rast1234** [comment]
hmm. i can reset the number when changing categories. you ok with that?

**Comment by Asasay** [comment]
Sure

**Pull request closed without merging**
